#!/bin/bash
cd $HOME/.mybackpack
git add mybackpack.db
git remote add https://github.com/ottacom/mybackpack_db.git
ts=$(date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s")
git commit -m "$ts"
git push -u origin master
