#!/bin/bash


search_db () {
	if [ ! -z "$Topic" ];then
       		sqlite3 $HOME/.mybackpack/mybackpack.db "select item_id,topic,raw_content,attachment_name from items where topic LIKE '%$Topic%';"
		exit 0
	fi
	if [ ! -z "$Content" ];then
                sqlite3 $HOME/.mybackpack/mybackpack.db "select item_id,topic,raw_content,attachment_name from items where raw_content LIKE '%$Content%';"
                exit 0
        fi
        sqlite3 $HOME/.mybackpack/mybackpack.db "select item_id,topic,raw_content,attachment_name from items where topic LIKE '%$Topic%' or raw_content LIKE '%$Content%';"
}

if [[ ! -e "$HOME/.mybackpack/mybackpack.db" ]]
then
	wget --quiet https://raw.githubusercontent.com/ottacom/mybackpack/master/schema -O $HOME/.mybackpack/schema
	sqlite3 $HOME/.mybackpack/mybackpack.db < $HOME/.mybackpack/schema
	echo "Database initialized"
else 
	read -p "Topic:" Topic
	read -p "Content:" Content
	search_db
fi

