#!/bin/bash

if [[ ! -e "$HOME/.mybackpack/mybackpack.db" ]]
then
	wget --quiet https://raw.githubusercontent.com/ottacom/mybackpack/master/schema -O $HOME/.mybackpack/schema
	sqlite3 $HOME/.mybackpack/mybackpack.db < $HOME/.mybackpack/schema
	echo "Database initialized"
else 
	item_id=$1
	if [[ -n "$item_id" ]]; then
                clear
		topic=$(sqlite3 $HOME/.mybackpack/mybackpack.db "select topic from items where item_id='$item_id';")
		raw_content=$(sqlite3 $HOME/.mybackpack/mybackpack.db "select raw_content from items where item_id='$item_id';")
		attachment_name=$(sqlite3 $HOME/.mybackpack/mybackpack.db "select attachment_name from items where item_id='$item_id';")
                echo "---Item number $item_id----"
                echo "Topic:$topic"            
                echo -e "Content:$raw_content"               
                if [ ! -z "$attachment_name" ];then

                        echo "Attachment:$attachment_name"   
                        echo "Type bpextract $1 to extract the document"

                fi
                echo "---End of item----"


        else
                sqlite3 $HOME/.mybackpack/mybackpack.db "select item_id,topic,raw_content,attachment_name from items;"
        fi
fi

